call npm install --global gulp@*
call npm install --save-dev gulp@*
call npm install --save-dev gulp-util@*
call npm install --save-dev gulp-uglify@*
call npm install --save-dev gulp-react@*
call npm install --save-dev gulp-html-replace@*
call npm install --save-dev vinyl-source-stream@*
call npm install --save-dev browserify@*
call npm install --save-dev watchify@*
call npm install --save-dev reactify@*
call npm install --save-dev gulp-streamify@*
call npm install --save-dev gulp-minify-css@*
call npm install --save-dev gulp-rename@*
call npm install --save-dev gulp-cleanhtml@*
call npm install --save-dev gulp-jshint@*
call npm install --save-dev jshint-stylish@*
call npm install --save-dev gulp-plumber@*